server:
  listen: ":6060"
  ws_listen: ":6061"
  agent_token: "change-me"
  log_level: "info"

routes:
  - domain: "test-pg-1.tcplb.nortezh.com"
    service: "example-pg-1.default.svc.cluster.local:5432"
    alpn:
      - postgresql

  - domain: "test-pg-2.tcplb.nortezh.com"
    service: "example-pg-2.default.svc.cluster.local:5432"
    alpn:
      - postgresql
