routes:
  - domain: "test-pg-1.tcplb.nortezh.com"
    service: "example-pg-1.default.svc.cluster.local:5432"
    alpn:
      - postgresql

  - domain: "test-pg-2.tcplb.nortezh.com"
    service: "example-pg-2.default.svc.cluster.local:5432"
    alpn:
      - postgresql
