image:
  tag: v3.6.8  # v3.6.9+ has a regression in PostgreSQL STARTTLS handling

deployment:
  kind: DaemonSet

service:
  enabled: false

ports:
  tcp:
    port: 6060
    hostPort: 6060
    protocol: TCP

additionalArguments:
  - "--entrypoints.tcp.address=:6060"
